@startuml

class App {
    main()
    start()
}

class InventoryTrackerController {
+ valueColumn: TableView<Item>
- valueColumn: TableView<Item, Double>
- serialNumberColumn: TableView<Item, Integer>
- nameColumn: TableView<Item, String>
- valueTextField: TextField
- serialNumberTextField: serialNumberTextField
- nameTextField: nameField
addButtonClicked()
loadButtonClicked()
removeButtonClicked()
saveButtonClicked()
searchByNameButtonClicked()
searchBySerialNumberButtonClicked()
searchByValueButtonClicked()
addItem()
loadList()
removeList()
saveList()
searchByName()
searchBySerialNumber()
searchByValue()
itemExists()
showAlert()
}

class Item {
- value: Double
- serialNumber: int
- name: String
getValue()
setValue()
getSerialNumber()
setSerialNumber()
getName()
setName()
}

class Serializer {
serializeTSV()
serializeHTML()
serializeJSON()

}

class Deserializer {
deserializeTSV()
deserializeHTML()
deserializeJSON()
}

javafx.Application <|-- App

App - InventoryTrackerController

InventoryTrackerController - Item
InventoryTrackerController - Serializer
InventoryTrackerController - Deserializer

@enduml