@startuml

class App {
    main()
    start()
}

class InventoryTrackerController {
+ valueColumn: TableView<Item>
- valueColumn: TableView<Item, Double>
- serialNumberColumn: TableView<Item, Integer>
- nameColumn: TableView<Item, String>
- valueTextField: TextField
- serialNumberTextField: serialNumberTextField
- nameTextField: nameField
addButtonClicked()
loadButtonClicked()
removeButtonClicked()
saveButtonClicked()
searchByNameButtonClicked()
searchBySerialNumberButtonClicked()
searchByValueButtonClicked()
addItem()
loadList()
loadJSON()
loadHTML()
loadTSV()
removeList()
saveList()
saveJSON()
saveTSV()
saveHTML()
searchByName()
searchBySerialNumber()
searchByValue()
itemExists()
showAlert()
parseCurrency()
}

class Item {
- value: Double
- serialNumber: int
- name: String
getValue()
setValue()
getSerialNumber()
setSerialNumber()
getName()
setName()
}

class JSONSerializer {
serialize()

}

class JSONDeserializer {
serialize()
}

javafx.Application <|-- App

App - InventoryTrackerController

InventoryTrackerController - Item
InventoryTrackerController - JSONSerializer
InventoryTrackerController - JSONDeserializer

@enduml